<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="winforms.datavisualization" Version="1.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.Kazhahmetov.Sprint6.Task5.V28.Lib\Tyuiu.Kazhahmetov.Sprint6.Task5.V28.Lib.csproj" />
  </ItemGroup>

</Project>